package com.pierluigicovone.microgradj.viz;

import com.pierluigicovone.microgradj.autograd.ComputationGraph;
import com.pierluigicovone.microgradj.autograd.DiffScalarNode;

import guru.nidi.graphviz.attribute.Color;
import guru.nidi.graphviz.attribute.Label;
import guru.nidi.graphviz.attribute.Rank;
import guru.nidi.graphviz.attribute.Shape;
import guru.nidi.graphviz.attribute.Style;
import guru.nidi.graphviz.engine.Format;
import guru.nidi.graphviz.engine.Graphviz;
import guru.nidi.graphviz.model.Factory;
import guru.nidi.graphviz.model.MutableGraph;
import guru.nidi.graphviz.model.MutableNode;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Renders a computation graph (built from {@link DiffScalarNode}) into a visual diagram.
 *
 * For each node in the graph, two graphical elements are produced:
 * a "value box" displaying data and gradient, and (for non-leaf nodes)
 * a smaller "operation circle" labeled with the operation symbol.
 * Edges connect parents → operation circle → value box.
 *
 * The output is rendered as a PNG image using the graphviz-java library.
 *
 * The code has been generated by Claude.ai
 * (this comment has been intentionally left explicit).
 */
public final class GraphRenderer {

    /**
     * Private constructor.
     */
    private GraphRenderer() {}

    /**
     * Renders the computation graph rooted at {@code root} and saves it as a PNG file.
     *
     * @param root       the root node of the graph (typically the final output)
     * @param outputPath the path of the PNG file to create
     * @throws IOException if the file cannot be written
     */
    public static void renderToFile(DiffScalarNode root, String outputPath) throws IOException {
        MutableGraph g = buildGraph(root);
        Graphviz.fromGraph(g).render(Format.PNG).toFile(new File(outputPath));
    }

    /**
     * Builds the graphviz-java MutableGraph from the computation graph.
     */
    private static MutableGraph buildGraph(DiffScalarNode root) {

        // Left-to-right layout, more readable than top-to-bottom for chains of operations.
        MutableGraph g = Factory.mutGraph("ComputationGraph")
                .setDirected(true)
                .graphAttrs().add(Rank.dir(Rank.RankDir.LEFT_TO_RIGHT));

        // Get all nodes via topological sort (order doesn't matter for rendering).
        List<DiffScalarNode> nodes = ComputationGraph.topologicalSort(root);

        // Map each DiffScalarNode to its corresponding "value box" graphical node.
        // We use System.identityHashCode to give each node a unique id, since
        // DiffScalarNode does not override equals/hashCode (and shouldn't).
        Map<DiffScalarNode, MutableNode> valueNodes = new HashMap<>();

        // Pass 1: create the "value box" for every node.
        for (DiffScalarNode n : nodes) {
            String id = "val_" + System.identityHashCode(n);
            MutableNode valueBox = Factory.mutNode(id)
                    .add(Shape.RECTANGLE)
                    .add(Style.FILLED)
                    .add(Color.rgb("E8F4F8").fill())
                    .add(Label.html(formatValueLabel(n)));
            valueNodes.put(n, valueBox);
            g.add(valueBox);
        }

        // Pass 2: for each non-leaf node, create the "operation circle"
        // and connect parents → operation → value.
        for (DiffScalarNode n : nodes) {
            if (n.getParents().isEmpty()) {
                continue; // leaf, no operation node needed
            }

            String opId = "op_" + System.identityHashCode(n);
            MutableNode opCircle = Factory.mutNode(opId)
                    .add(Shape.CIRCLE)
                    .add(Style.FILLED)
                    .add(Color.rgb("FFE0B2").fill())
                    .add(Label.of(n.getOperation()));
            g.add(opCircle);

            // Parents' value boxes → this operation circle
            for (DiffScalarNode parent : n.getParents()) {
                valueNodes.get(parent).addLink(opCircle);
            }

            // This operation circle → this node's value box
            opCircle.addLink(valueNodes.get(n));
        }
        return g;
    }

    /**
     * Builds the HTML-style label for a value box, showing data and gradient.
     */
    private static String formatValueLabel(DiffScalarNode n) {
        return String.format(
                "<<B>data</B> %.4f<BR/><B>grad</B> %.4f>",
                n.getData(), n.getGrad()
        );
    }
}